name: camiseta_futbolera
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.0.0
  provider: ^6.0.5
  google_sign_in: ^6.1.0
  http: ^1.1.0
  flutter_launcher_icons: ^0.14.3
  shared_preferences: ^2.5.3
  google_maps_flutter: ^2.3.0
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/logo.png
    - assets/icons/Google.png
    - assets/icons/usuario.jpg
    - assets/icons/llave.png
    - assets/icons/email.png
    - assets/icons/nombreApp.png
    - assets/icons/logoEstrellas.png
    - assets/icons/contrasena.png
    - assets/icons/telefono.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"
  adaptive_icon_background: "#56b8f9"  
  adaptive_icon_foreground: "assets/icons/logo.png"
  
